# Generated by Django 2.2 on 2022-07-07 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
